# CART SERVICE
cart_service_name: cartservice
cart_service_image: gcr.io/google-samples/microservices-demo/cartservice:v0.6.0
spanner_connection_string: "projects/PROJECT_ID/instances/SPANNER_INSTANCE_NAME/databases/SPANNER_DATABASE_NAME"
spanner_db_user_sa: "spanner-db-user-sa@PROJECT_ID.iam.gserviceaccount.com"
service: 
  port: 7070
  type: ClusterIP