---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.shipping_service_name }}-{{ .Release.Revision }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.shipping_service_name }}-{{ .Release.Revision }}
  template:
    metadata:
      labels:
        app: {{ .Values.shipping_service_name }}-{{ .Release.Revision }}
    spec:
      tolerations:
      - key: "os"
        operator: "Equal"
        value: "linux"
        effect: "NoSchedule"     
      containers:    
      - env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
        image: {{ .Values.shipping_service_image }}
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50051
        name: server
        ports:
        - containerPort: 50051
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50051
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: {{ .Values.shipping_service_name }}