FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /src

COPY [".", "."]

RUN dotnet restore "aspnet6.csproj"

RUN dotnet publish "MyApp.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet", ".dll"]
