name: Containerisation CI
on:
  workflow_dispatch:
  push:
    branches: 
      - Dev
      - Stage
      - main
    paths: 
      - micro-service/Helm-Charts/frontend/**
      - micro-service/online-botique-src/frontend/**
      - .github/workflows/containerisation-ci.yml

jobs:
  Image-Build:
    name: 'Docker Build'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: /home/runner/work/Demo/Demo/micro-service

    steps:
            
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Dependencies
        run: |
            ls
            cd online-botique-src/frontend/
            go mod tidy
            docker build -t gcr.io/${{vars.PROJECT_ID}}/frontend:${{github.run_number}} .

      - name: List Docker Image
        run: |
            docker images 

      # - name: gcloud 
      #   uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      #   with:
      #     service_account_key: ${{ secrets.SA_KEY }}
      #     project_id: ${{ vars.PROJECT_ID }}  

      - run: |-
          echo "gcloud --quiet auth configure-docker"
          # gcloud --quiet auth configure-docker

      - name: docker build and push
        run: |
          echo "Pushing the docker image"
          # docker push gcr.io/${{vars.PROJECT_ID}}/frontend:${{github.run_number}}   
      
      - name: Update image name in Helm Chart & deployment.yaml
        run: |
          sed -i 's#frontend_image#gcr.io/${{vars.PROJECT_ID}}/frontend:${{github.run_number}}#g' ${{ github.workspace }}/micro-service/Helm-Charts/frontend/values.yaml
          sed -i 's#containerised_image#gcr.io/${{vars.PROJECT_ID}}/frontend:${{github.run_number}}#g' ${{ github.workspace }}/micro-service/containerised-app-deployment.yaml

      - name: Creating artifact
        run: echo "Creating artifact"
        
      - uses: actions/upload-artifact@main
        name: Uploading Helm Artifact
        with:
          name: Deployment-HELM-Artifacts
          path: ${{ github.workspace }}/micro-service/Helm-Charts/frontend/*          

      - uses: actions/upload-artifact@main
        name: Uploading Deployment YAML Artifact
        with:
          name: Deployment-YAML-Artifacts
          path: ${{ github.workspace }}/micro-service/containerised-app-deployment.yaml 